name: Manual Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      selected_os:
        description: 'Target OS (ubuntu-latest, windows-latest, macos-latest, or all)'
        required: false
        default: 'all'

jobs:
  run-on-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ github.event.inputs.selected_os }}

    steps:
      - name: Run job on ${{ matrix.os }}
        if: ${{ github.event.inputs.selected_os == 'all' || github.event.inputs.selected_os == matrix.os }}
        run: echo "Running on ${{ matrix.os }}"
