name: Run on Selected OS Only

on:
  workflow_dispatch:
    inputs:
      selected_os:
        description: 'Choose the OS to run the job on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  run-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [${{ github.event.inputs.selected_os }}]  # Only run the selected OS
      fail-fast: false

    steps:
      - name: Show selected OS
        run: echo "Running on ${{ matrix.os }}"
