name: Manual Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      target_os:
        description: 'Target OS to run the job on (e.g., ubuntu-latest, windows-latest, macos-latest)'
        required: false
        default: ''

jobs:
  run-on-os:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.inputs.target_os == '' || matrix.os == github.event.inputs.target_os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Print OS
        run: echo "Running on ${{ matrix.os }}"
