name: Manual Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      selected_os:
        description: 'Target OS (ubuntu-latest, windows-latest, macos-latest, or all)'
        required: false
        default: 'all'

jobs:
  run-on-os:
    strategy:
      matrix:
        os: ${{ fromJson(github.event.inputs.selected_os: != 'all' && github.event.inputs.selected_os: != '' && format('["{0}"]', github.event.inputs.selected_os:) || '["ubuntu-latest", "windows-latest", "macos-latest"]') }}
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo OS
        run: echo "Running on ${{ matrix.os }}"
