name: Two Jobs with Step-Level Conditional (Final)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  # Job A: Runs Job-A on both Ubuntu and macOS.
  # Explicitly configured to fail the Ubuntu instance for demonstration.
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false # Ensures all matrix jobs run even if one fails
      matrix:
        os_runner: [ubuntu-latest, macos-latest] # Our two runners
    outputs:
      status_ubuntu: ${{ steps.run_job_a.outputs.current_status }}
      status_macos: ${{ steps.run_job_a.outputs.current_status }}
    steps:
      - name: Run Job-A logic
        id: run_job_a 
        run: |
          echo "Running Job-A on ${{ matrix.os_runner }}..."
          # --- SCENARIO: SIMULATE FAILURE FOR UBUNTU-LATEST ---
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating a controlled failure for Job-A on ubuntu-latest."
            exit 1 # A non-zero exit code makes the step (and job instance) fail.
          fi
          echo "Job-A on ${{ matrix.os_runner }} completed successfully."
          echo "Current status for ${{ matrix.os_runner }}: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "current_status=${{ job.status }}" >> $GITHUB_OUTPUT # Output current job status (success/failure)

  # Job B: Runs on matrix, with conditional logic handled within its steps.
  # Using if: always() to ensure it's not skipped due to upstream failures.
  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a # Job B depends on all instances of Job A completing.
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false # Ensure all matrix jobs for Job B are created, even if one condition leads to skip
      matrix:
        os_runner: [macos-latest] # Re-defines the matrix for Job B.
    
    steps:
      - name: Check Job-A status and run Job-B logic
        if: (matrix.os_runner == 'macos-latest' && needs.job-a.outputs.status_macos == 'success')
        run: |
          echo "--------------------------------------------------------"
          echo "SUCCESS: Running Job-B logic on ${{ matrix.os_runner }}!"
          echo "Job-A on this runner succeeded. Proceeding with Job-B tasks."
          echo "--------------------------------------------------------"
          # Add your actual Job-B commands here (e.g., build, test, deploy)
