name: Two Jobs with Matrix and Conditional Execution

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  job-a:
    name: Job-A on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Simulate Job-A logic
        id: job_a_step
        run: |
          echo "Running Job-A on ${{ matrix.os }}..."
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "Simulating failure on ubuntu-latest"
            exit 1
          fi
          echo "Job-A succeeded on ${{ matrix.os }}"

      - name: Save status to file
        if: always()
        run: echo "${{ job.status }}" > status-${{ matrix.os }}.txt

      - name: Upload status artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: status-${{ matrix.os }}
          path: status-${{ matrix.os }}.txt

  job-b:
    name: Job-B on ${{ matrix.os }}
    needs: job-a
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Download status artifact
        uses: actions/download-artifact@v4
        with:
          name: status-${{ matrix.os }}
          path: ./status

      - name: Read status and conditionally run Job-B
        run: |
          STATUS=$(cat ./status/status-${{ matrix.os }}.txt)
          echo "Job-A status for ${{ matrix.os }}: $STATUS"
          if [ "$STATUS" == "success" ]; then
            echo "Running Job-B logic on ${{ matrix.os }}"
            # Add your actual Job-B logic here
          else
            echo "Skipping Job-B on ${{ matrix.os }} because Job-A failed"
          fi
