# .github/workflows/ubuntu-fails-scenario.yml

name: Two Jobs with Conditional Logic

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering for easy testing

jobs:
  # Job A: Runs on both Ubuntu and macOS.
  # Explicitly fails the Ubuntu instance.
  job-a:
    name: Run on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        os_runner: [ubuntu-latest, macos-latest]
    
    # Dynamically define outputs for each runner.
    outputs:
      status: ${{ steps.set_status.outputs.status }}

    steps:
      - name: Run Job-A logic
        id: run_job_a
        run: |
          echo "Running Job-A on ${{ matrix.os_runner }}..."
          
          # --- SCENARIO: SIMULATE FAILURE FOR UBUNTU-LATEST ---
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating a controlled failure for Job-A on ubuntu-latest."
            exit 1 # A non-zero exit code makes the step fail.
          fi
          # --- END SCENARIO ---
          
          echo "Job-A on ${{ matrix.os_runner }} completed successfully."
      
      - name: Set job output status
        id: set_status
        if: always()
        run: |
          # Use `github.job.status` to capture the actual status (success/failure) of the job.
          echo "status=${{ github.job.status }}" >> $GITHUB_OUTPUT

  # Job B: Runs on matrix, but conditionally based on Job-A.
  job-b:
    name: Run on ${{ matrix.os_runner }}
    needs: job-a # Job B depends on all instances of Job A completing.
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        os_runner: [ubuntu-latest, macos-latest]
    
    # Use a job-level 'if' to ensure Job B instances only run if their corresponding Job A succeeded.
    if: needs.job-a.result == 'success'
    
    steps:
      - name: Run Job-B logic
        run: |
          echo "--------------------------------------------------------"
          echo "SUCCESS: Running Job-B logic on ${{ matrix.os_runner }}!"
          echo "Job-A on this runner succeeded. Proceeding with Job-B tasks."
          echo "--------------------------------------------------------"
          # Add your actual Job-B commands here (e.g., build, test, deploy)
