name: Two Jobs with Step-Level Conditional (Ubuntu Fails)

on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  # Job A: Runs Job-A on both Ubuntu and Windows.
  # We will explicitly make the Ubuntu instance fail.
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        os_runner: [ubuntu-latest, macos-latest]
    outputs:
      status_ubuntu: ${{ steps.run_job_a.outputs.status }}
      status_macos: ${{ steps.run_job_a.outputs.status }}
    steps:
      - name: Run Job-A logic
        id: run_job_a # ID to capture the current job's status
        run: |
          echo "Running Job-A on ${{ matrix.os_runner }}..."
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating a controlled failure for Job-A on ubuntu-latest."
            exit 1 # A non-zero exit code makes the step (and job instance) fail.
          fi
          echo "Job-A on ${{ matrix.os_runner }} completed successfully."
          echo "Current status for ${{ matrix.os_runner }}: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "status=${{ job.status }}" >> $GITHUB_OUTPUT # Output current job status (success/failure)
        continue-on-error: true
  # Job B: Runs on matrix, but conditional logic is handled within its steps.
  # This demonstrates how the Job B instance for ubuntu-latest will be affected.
  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a # Job B depends on all instances of Job A completing.
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        os_runner: [ubuntu-latest, macos-latest] 
        
    steps:
      - name: Check Job-A status and run Job-B logic
        if: |
          (matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
          (matrix.os_runner == 'macos-latest' && needs.job-a.outputs.status_macos == 'success')
        run: |
          echo "--------------------------------------------------------"
          echo "SUCCESS: Running Job-B logic on ${{ matrix.os_runner }}!"
          echo "Job-A on this runner succeeded. Proceeding with Job-B tasks."
          echo "--------------------------------------------------------"
          # Add your actual Job-B commands here (e.g., build, test, deploy)
          
      - name: Indicate skip (if condition not met)
        if: |
          !((matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
            (matrix.os_runner == 'macos-latest' && needs.job-a.outputs.status_macos == 'success'))
        run: |
          echo "--------------------------------------------------------"
          echo "SKIPPED: Job-B on ${{ matrix.os_runner }} was skipped."
          echo "Reason: Job-A on the same runner did NOT succeed."
          echo "--------------------------------------------------------"
