name: Matrix Runner Workflow
 
on:
  push:
    branches:
      - main
  workflow_dispatch: 
 
jobs:
  job-a:
    name: Job-A on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    outputs:
      ubuntu-latest-status: ${{ steps.set-result.outputs.ubuntu-latest }}
      macos-latest-status: ${{ steps.set-result.outputs.macos-latest }}
    steps:
      - name: Run Job-A logic
        run: echo "Running Job-A on ${{ matrix.runner }}"
 
      - name: Set result
        id: set-result
        run: |
          echo "${{ matrix.runner }}=success" >> $GITHUB_OUTPUT
 
  job-b:
    name: Job-B on ${{ matrix.runner }}
    needs: job-a
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]
    if: |
       (matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
       (matrix.os_runner == 'macos-latest' && needs.job-a.outputs.status_macos == 'success')
    steps:
      - run: echo "Running Job-B on ${{ matrix.runner }} because Job-A succeeded on the same runner"
 
