name: Two Jobs with Step-Level Conditional

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job A: Runs Job-A on both Ubuntu and Windows
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      matrix:
        os_runner: [ubuntu-latest, windows-latest]
    outputs:
      status_ubuntu: ${{ steps.run_job_a.outputs.status }}
      status_windows: ${{ steps.run_job_a.outputs.status }}
    steps:
      - name: Run Job-A logic
        id: run_job_a
        run: |
          # echo "Running Job-A on ${{ matrix.os_runner }}..."
          # Simulate failure for ubuntu-latest for testing
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating failure for ubuntu-latest."
            exit 1
          fi
          # echo "Current status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          # echo "status=${{ job.status }}" >> $GITHUB_OUTPUT # Output current job status

  # Job B: Runs on matrix, but conditional logic is within its steps
  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a # Depends on Job-A completing all its matrix runs
    runs-on: ${{ matrix.os_runner }}
    strategy:
      matrix:
        os_runner: [ubuntu-latest, windows-latest]
    steps:
      - name: Check Job-A status and run Job-B logic
        if: |
          (matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
          (matrix.os_runner == 'windows-latest' && needs.job-a.outputs.status_windows == 'success')
        run: |
          echo "Running Job-B on ${{ matrix.os_runner }} because Job-A on ${{ matrix.os_runner }} succeeded."
      - name: Indicate skip
        if: |
          !((matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
            (matrix.os_runner == 'windows-latest' && needs.job-a.outputs.status_windows == 'success'))
        run: |
          echo "Job-B on ${{ matrix.os_runner }} skipped due to Job-A failure on the same runner."
