# .github/workflows/strictly-two-jobs-conditional.yml

name: Strictly Two Jobs Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job-A: Runs on matrix, collects individual runner results, and *aggregates them*.
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }} # Use the OS runner directly
    strategy:
      matrix:
        os_runner: [ubuntu-latest, windows-latest] # Our two runners
    outputs:
      aggregated_statuses: ${{ steps.aggregate_statuses.outputs.statuses_json }}
      ubuntu_latest_status: ${{ steps.set_status_output.outputs.ubuntu_status }}
      windows_latest_status: ${{ steps.set_status_output.outputs.windows_status }}
    
    steps:
      - name: Run Job-A logic
        run: |
          echo "Running Job-A logic on ${{ matrix.os_runner }}..."
          echo "Job-A on ${{ matrix.os_runner }} completed with status: ${{ job.status }}"
        
      - name: Set Specific Status Output for Aggregation
        if: always() # Ensure this always runs to capture status, even if previous step failed
        id: set_status_output
        run: |
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "ubuntu_status=${{ job.status }}" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os_runner }}" == "windows-latest" ]; then
            echo "windows_status=${{ job.status }}" >> $GITHUB_OUTPUT
          fi


  # Job-B: Runs on matrix, depends on Job-A's per-runner success.
  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a # Depends on Job-A completing (all matrix runs)
    runs-on: ${{ matrix.os_runner }} # Uses the OS runner directly from its own matrix
    strategy:
      matrix:
        os_runner: [ubuntu-latest, windows-latest] # Re-define the matrix for job-b
    
    # This is the complex IF condition that references outputs from job-a directly.
    # It works because 'needs.job-a.outputs.ubuntu_latest_status' and
    # 'needs.job-a.outputs.windows_latest_status' are specific, non-matrix outputs
    # from job-a, and matrix.os_runner is from job-b's *own* matrix expansion.
    if: |
      (matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.ubuntu_latest_status == 'success') ||
      (matrix.os_runner == 'windows-latest' && needs.job-a.outputs.windows_latest_status == 'success')
      
    steps:
      - name: Execute Job-B logic
        run: |
          echo "Running Job-B on ${{ matrix.os_runner }} because Job-A on ${{ matrix.os_runner }} succeeded."
