name: Two Jobs with Step-Level Conditional (Final Fix)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  # Job A: Runs Job-A on both Ubuntu and macOS.
  # Explicitly configured to fail the Ubuntu instance for demonstration.
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false 
      matrix:
        os_runner: [ubuntu-latest, macos-latest] # Our two runners
    outputs:
      status_ubuntu: ${{ steps.run_job_a.outputs.current_status }}
      status_macos: ${{ steps.run_job_a.outputs.current_status }}
    steps:
      - name: Run Job-A logic
        id: run_job_a # ID to capture the current job's status
        run: |
          echo "Running Job-A on ${{ matrix.os_runner }}..."
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating a controlled failure for Job-A on ubuntu-latest."
            exit 1 # A non-zero exit code makes the step (and job instance) fail.
          fi
          echo "Job-A on ${{ matrix.os_runner }} completed successfully."
          echo "Current status for ${{ matrix.os_runner }}: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "current_status=${{ job.status }}" >> $GITHUB_OUTPUT # Output current job status (success/failure)

  # Job B: Runs on matrix, with conditional logic handled within its steps.
  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a 
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false 
      matrix:
        os_runner: [ubuntu-latest, macos-latest] 
    if: |
      (matrix.os_runner == 'ubuntu-latest' && needs.job-a.outputs.status_ubuntu == 'success') ||
      (matrix.os_runner == 'macos-latest' && needs.job-a.outputs.status_macos == 'success')
    
    steps:
      - name: Check Job-A status and run Job-B logic
        run: |
          echo "--------------------------------------------------------"
          echo "SUCCESS: Running Job-B logic on ${{ matrix.os_runner }}!"
          echo "Job-A on this runner succeeded. Proceeding with Job-B tasks."
          echo "--------------------------------------------------------"
