name: Workflow 2

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository that triggered this workflow'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my test task
        run: |
          echo "Executing the test task for Workflow 2..."
          # Your actual test or deployment commands go here.
          sleep 45 # Simulate a task taking time
          echo "Workflow 2 completed successfully."
