name: Two Jobs with Step-Level Conditional (Final Fix)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  job-a:
    name: Job-A on ${{ matrix.os_runner }}
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        os_runner: [ubuntu-latest, macos-latest]
    outputs:
      ubuntu_status: ${{ steps.set_status.outputs.status }}
      macos_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Run Job-A logic
        id: run_job_a
        run: |
          echo "Running Job-A on ${{ matrix.os_runner }}..."
          if [ "${{ matrix.os_runner }}" == "ubuntu-latest" ]; then
            echo "Simulating failure on ubuntu-latest"
            exit 1
          fi
          echo "Success on ${{ matrix.os_runner }}"
        continue-on-error: true

      - name: Set status output
        id: set_status
        run: |
          if [ "${{ steps.run_job_a.outcome }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

  job-b:
    name: Job-B on ${{ matrix.os_runner }}
    needs: job-a
    runs-on: ${{ matrix.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_runner: ubuntu-latest
            condition: ${{ needs.job-a.outputs.ubuntu_status == 'success' }}
          - os_runner: macos-latest
            condition: ${{ needs.job-a.outputs.macos_status == 'success' }}
    if: ${{ matrix.condition }}
    steps:
      - name: Run Job-B logic
        run: echo "Running Job-B on ${{ matrix.os_runner }} because Job-A succeeded."
